---
- hosts: all-servers
  user: pi
  sudo: true
  sudo_user: root
  gather_facts: false
  vars:
    ansible_path: "{{ lookup('env','ANSIBLE_WORK_DIR') }}"
  tasks:
    - name: deploying blue to bottom right
      shell: nohup sudo /home/pi/piglow/blue
      when: inventory_hostname in groups['bottomright']  
  
    - name: deploying red to bottom left
      shell: nohup sudo /home/pi/piglow/red
      when: inventory_hostname in groups['bottomleft']  
      
    - name: deploying green to top right
      shell: nohup sudo /home/pi/piglow/green
      when: inventory_hostname in groups['topright']  
    
    - name: deploying orange to top right
      shell: nohup sudo /home/pi/piglow/orange
      when: inventory_hostname in groups['topleft']  
